export enum LOYALTY_ERROR_CODE {
    ERROR_INVALID_FORMAT_OR_MISSING_FIELD = 'INVALID_FORMAT_OR_MISSING_FIELD',
    ERROR_PHONE_ALREADY_EXISTS = 'ALREADY_EXISTS',
    ERROR_ORDER_CODE_ALREADY_EXISTS = 'ALREADY_EXISTS',
    ERROR_MEMBER_NOT_FOUND = 'NOT_FOUND',
    ERROR_ENROLLMENT_FORM_CODE_NOT_FOUND = 'NOT_FOUND',
    ERROR_ACTIVITY_CODE_NOT_FOUND = 'NOT_FOUND',
    ERROR_MEMBER_STATUS_NOT_ELIGIBLE = 'NOT_ELIGIBLE',
    ERROR_ORDER_RETURN_LIMIT_EXCEEDED = 'NOT_ELIGIBLE',
    ERROR_INSUFFICIENT_BALANCE_FOR_POINTS_USAGE = 'NOT_ELIGIBLE',
}