version: 3.9+'
services:
  app:
    image: famimavn/loyalty-retry:latest
    container_name: familymart
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - /home/itsoftware/familymart/backend/$${LOG_PATH}$$:/app/logs
    command: npm run start:prod
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - /home/itsoftware/familymart/backend/redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --bind 0.0.0.0
      --protected-mode no
      --user ${REDIS_USER} on >${REDIS_PASSWORD} allcommands allkeys ~*
# --requirepass ${REDIS_PASSWORD}
