version: '3.9+'

services:
  app:
    build: .
    container_name: famima-backend
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    command: npm run start:dev

  redis:
    image: redis:8
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly yes
      - --appendfsync everysec
      - --save 900 1
      - --save 300 10
      - --save 60 10000

volumes:
  redis-data:
