version: '3.9+'

services:
  app:
    build: .
    container_name: familymart-backend
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - ${LOG_PATH}:/app/logs
    command: npm run start

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --appendonly yes
      - --appendfsync everysec
      - --save 900 1
      - --save 300 10
      - --save 60 10000

volumes:
  redis-data:
